### PR TITLE
Use minizip to replace libgsf

### PR DESCRIPTION
**Pull request by yetist**
The previous closed PR, see #975

### CODE REVIEW

**Comment by yetist** [comment]
CI is disabled?

**Comment by alerque** [comment]
This is much better than the previous iteration, thank you. Minizip seems like a reasonable dependency—I don't know about other platforms but at least for Arch Linux it is in the [core] repository so it is an easy dependency to build with.

**Comment by yetist** [comment]
minizip is available in most distro, see https://pkgs.org/download/minizip

**Comment by karlkleinpaste** [comment]
this one i like a whole lot more. simple and direct. thanx.

**Comment by karlkleinpaste** [comment]
ok, i'm a little bit bothered now. by the time you submit a pull req, i assume that you've done some testing of your own, starting with successful build. i'm on up to date F31.
screenshot1
zip.h only includes mz_compat.h, which does not know these symbols.

**Comment by karlkleinpaste** [comment]
in fact, they're not known at all.

$ grep Z_BEST *
$ grep Z_DEFL *
$

**Comment by greg-hellings** [comment]
https://travis-ci.org/github/crosswire/xiphos/builds/676272298 CI was never updated for this PR, either. I don't know why Travis didn't report here in the builds, but the build did execute and failed (missing the new dep, not the same error as you're seeing @karlkleinpaste)

**Comment by greg-hellings** [comment]
Those symbols exist in /usr/include/zlib.h for me, which is coming from zlib-devel package.

**Comment by karlkleinpaste** [comment]
by this evening, i need either a _tested_ fix or i'll hit it with reset --hard HEAD~ and push --force.

**Comment by greg-hellings** [comment]
Working on it.

Out of curiosity... what does libgsf/minizip actually DO for Xiphos?

**Comment by yetist** [comment]
I forgot to update travis.yml, but I don't understand why Travis CI didn't report build status.

**Comment by karlkleinpaste** [comment]
module archival, for single file move to other places, or...just for archives.
see mod.mgr, maintenance page, buttons at the bottom.

**Comment by greg-hellings** [comment]
I just submitted #1004 that fixes the build errors (in my system).

However, when I archive KJV I get a 4.0KB zip file and a handful of GLib-CRITICAL messages in the console of the form:
```
(xiphos:885992): GLib-CRITICAL **: 12:50:28.057: g_dir_read_name: assertion 'dir != NULL' failed

(xiphos:885992): GLib-CRITICAL **: 12:50:28.057: g_dir_close: assertion 'dir != NULL' failed
```

I don't have time this second to dive into the functionality deficiencies, but the build error is, at least, fixed if someone else wants to revisit the functional testing.

**Comment by karlkleinpaste** [comment]
i appreciate the fix pull, but at this point id rather see @yetist deal with it directly, both build and functionally, i.e., do some test archivals via mod.mgr and verify the results make sense.

**Comment by yetist** [comment]
I use Archlinux, build and create zip file is  fine.

**Comment by alerque** [comment]
@greg-hellings I am also able to build this with no issue, and it generates valid zip files. I also don't see the same Glib error you are seeing. I do get two messages when I hit the "Archive" button when the confirmation dialog pops up asking "Archive these modules?". The Yes/No buttons seem to work, but drawing the confirmation modal gives these on the console:

```
(xiphos:1294760): GLib-GObject-WARNING **: 22:00:15.602: invalid cast from 'GtkBox' to 'GtkButtonBox'

(xiphos:1294760): Gtk-CRITICAL **: 22:00:15.603: gtk_button_box_set_layout: assertion 'GTK_IS_BUTTON_BOX (widget)' failed
```

**Comment by greg-hellings** [comment]
@alerque I also see those warnings, but I definitely got the two others. And I need to directly include the zlib.h header directly in utilities.c in order to build successfully.

**Comment by alerque** [comment]
@yetist Arch Linux systems pretty much all have zlib by default. Are you sure you didn't reference something there by mistake that would make it a dependency, but not show up when building on Arch?

**Comment by karlkleinpaste** [comment]
all right... i've had a busy day at work that's finally winding down. where are we at this point? @yetist says he builds fine without changes on arch. @alerque confirms this. F31 chokes on it in my case, as well as whatever @greg-hellings is using (i assume F-something-recent). shall i merge @greg-hellings' 1004 PR to fix this whole thing?

**Comment by greg-hellings** [comment]
Worth noting:

Fedora 31 has minizip 2.9.1, which both Karl and I are on.
Arch ships with minizip 1.2.11.

The /usr/include/minizip/zip.h header on Arch has a `#include <zlib.h>` line in it, while the version on Fedora from a much later version of minizip does not.

It seems the discrepancy might be due to Arch having an impossibly ancient version of minizip by default. I wonder if that also accounts for the differences in the ZIP archives and warnings we're seeing.

**Comment by alerque** [comment]
@greg-hellings Good find. If the [zlib website](https://www.zlib.net/) which is the original home for minizip is to be believed, 1.2.11 is the very latest release. It looks like Fedora is packaging [this fork](https://github.com/nmoinvaz/minizip).

**Comment by karlkleinpaste** [comment]
1.2.11 is the very latest, and 3+ yrs old? really?
and i thought xiphos having gone 2 yrs was positively petrified.

**Comment by alerque** [comment]
It looks like Fedora and CentOS have both the original and forks available. The Travis dependencies need to specify they want the 1.2 package: `minizip1.2`. There is probably something to do to fix the include statement as well but I'm not sure what that is.

**Comment by greg-hellings** [comment]
Looks like the comparable package in Fedoraland is minizip-compat. The two are incompatible with one another. I can build without modification using minizip-compat, but the archive still fails to create.

**Comment by greg-hellings** [comment]
Still seeing
```
(xiphos:894861): GLib-CRITICAL **: 14:51:11.799: g_dir_read_name: assertion 'dir != NULL' failed

(xiphos:894861): GLib-CRITICAL **: 14:51:11.799: g_dir_close: assertion 'dir != NULL' failed
```

**Comment by karlkleinpaste** [comment]
i am uncomfortable building against packages named -compat because they have a tendency to disappear entirely in the N+1st release.

**Comment by alerque** [comment]
@greg-hellings Are you sure the include detected and used libminizip.so.1 in preference to 2? You might need a CMake adjustment to request the `so.1` version somehow.

**Comment by greg-hellings** [comment]
Correction: the archive creates but only includes the .conf file. No data files. Is that correct?

**Comment by greg-hellings** [comment]
@alerque 
```bash
$ ldd /usr/local/bin/xiphos | grep zip
	libminizip.so.1 => /lib64/libminizip.so.1 (0x00007f6afe5f2000)
```

I completely removed and uninstalled minizip in favor of minizip-compat

**Comment by karlkleinpaste** [comment]
no, of course not. the point of archival is to create a single file you can stow away or send to some other system.

**Comment by alerque** [comment]
@greg-hellings I get data files too.

**Comment by greg-hellings** [comment]
Oh man. This seems to be something wonky on my system. Somewhere I ended up with kjv.conf installed but I don't actually have the module data files. So this seems to be behaving in exactly the way we would expect.

**Comment by karlkleinpaste** [comment]
then if @greg-hellings has it actually working, using your updates in 1004, then i'll merge and we can declare victory and go home.

**Comment by greg-hellings** [comment]
Victory has been declared! Re-installing the module with mod.mgr and running the archive has cleared both the console warnings and resulted in a properly built ZIP archive. And that's using the native minizip in Fedora.

Still needs the direct inclusion of zlib.h in Xiphos, though, as done in #1004

**Comment by yetist** [comment]
I think someone should check why travis did not report the build status here, so we can know the build status on other distro.

**Comment by greg-hellings** [comment]
I'm beginning to wonder if it has something to do with Travis-ci.org versus .com. They've been slowly migrating from the org to the com for a long time. But I've recently seen them moving more rapidly.

I'll experiment with that in the future if we don't decide to move to Git Hub Actions entirely.

**Pull request merged**
