### PR TITLE
Fixed issue #810

### PR DESCRIPTION
**Pull request by yetist**
Please see issue #810

### CODE REVIEW

**Comment by yetist** [comment]
Now it works.
```
$ ldd ./build/default/src/gnome2/xiphos|grep gtk
	libgtkhtml-editor-4.0.so.0 => /usr/lib/libgtkhtml-editor-4.0.so.0 (0x00007f5a69d3f000)
	libgtkhtml-4.0.so.0 => /usr/lib/libgtkhtml-4.0.so.0 (0x00007f5a69a68000)
	libwebkit2gtk-4.0.so.37 => /usr/lib/libwebkit2gtk-4.0.so.37 (0x00007f5a66e2e000)
	libgtk-3.so.0 => /usr/lib/libgtk-3.so.0 (0x00007f5a6652d000)
	libjavascriptcoregtk-4.0.so.18 => /usr/lib/libjavascriptcoregtk-4.0.so.18 (0x00007f5a63dd4000)

```

**Comment by yetist** [comment]
This patch may have fixed issue #810 #806 #756. Has anyone tested it?

**Comment by karlkleinpaste** [comment]
i will deal with all this soon.

**Comment by karlkleinpaste** [comment]
finally looking at this, and regrets for delay.

but my initial reaction is to see that, with this patch, xiphos utterly ignores saved size preference. it always opens in default tiny state.

**Comment by karlkleinpaste** [comment]
without the patch, that is, with code in latest master state, i rebuilt all of gtk2/wk1, gtk3/wk1, and gtk3/wk2 configurations. they all display normally.

somebody convince me that this problem was not a gtk3 or wk2 bug that has been fixed relatively recently.

**Comment by yetist** [comment]
ok, now this patch can use the saved window size.

According to my test, this problem only occurs when gtk3 and WebKit2 are enabled.

I use archlinux, gtk3 version is 3.22.17, webkit2gtk version is 2.16.6.

**Comment by karlkleinpaste** [comment]
fyi 4.0.6 to be released by the weekend.

**Comment by yetist** [comment]
Good.
This patch just allows Xiphos to work on gtk3 and webkit2. But that may not be the best way.

According to the WebKit documents, The new WebKitWebView should not be displayed to the user until the “ready-to-show” signal is emitted. Please see [here](https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebView.html#WebKitWebView-create).
And without this patch, the width and height of the WebKitWebView in my test is always 0.

**Pull request merged**
