### PR TITLE
Handle tabs more like browsers do

### LINKED ISSUE #1147: Handle tabs more like browsers do
I would love to see tabs handled in the same way as modern browsers. Here are some examples:
- Open verses in a new tab via context menu or middle click (specifically in the Verse List panel, but maybe there are other places that make sense, too)
- Move existing tabs around by either click-and-drag or Ctrl+Shift+[PgUp/PgDown]
- Close existing tabs via middle click (anywhere on the tab) or Ctrl+W
- Re-open closed tabs via Ctrl+Shift+~~W~~T (not as desirable as the others)

These changes would help power users navigate around more quickly, as they are used to with their browser.

---

**Edit:** I've started work on this and have created the following checklist for myself and others to keep track of my progress. I'll be ignoring Ctrl+Shift+~~W~~T for now due to my unfamiliarity with the project.

- [x] Rearrange tabs by click-and-drag
- [x] Middle click to open in new tab (already done by someone else, thank you!)
- [x] Middle click any tab to close it
- [x] Click "X" icon on any tab to close it, not just the current tab
- [x] Shortcuts
  - [x] Ctrl-W: Close current tab
  - [x] Ctrl-Tab / ~~Ctrl-PgDown~~: Navigate to next tab
  - [x] Ctrl-Shift-Tab / ~~Ctrl-PgUp~~: Navigate to previous tab
  - [x] Ctrl-Shift-PgDown: Reorder current tab to the right
  - [x] Ctrl-Shift-PgUp: Reorder current tab to the left

### PR DESCRIPTION
**Pull request by nwalkewicz**
This PR is based off of issue #1147.

In short, the purpose of this PR is to add various shortcuts/behaviors that make the tab system work a bit more as someone would expect coming from modern browsers. For a full list of changes, please see the original issue or refer to the names of these commits.

I ensured that formatting and code styles are as similar as the rest of the project as possible. Thank you for considering my contribution!

Closes #1147

### CODE REVIEW

**Comment by nwalkewicz** [comment]
I removed the Ctrl-PgUp/PgDown shortcuts for notebook_main because the shortcut seems to have already been used for the Standard/Parallel view's tabs.

**Comment by nwalkewicz** [comment]
@karlkleinpaste Just fixed the issue I acknowledged in my last comment, would you mind reviewing this?

If you're curious, I just wrongly assumed tab positions were swapped and didn't account for them being shifted. Nothing to do with parallel tabs after all.

**Comment by karlkleinpaste** [comment]
i've had a weirdly busy week but i will check on this sometime over the weekend. sorry for delay.

**Comment by nwalkewicz** [comment]
No worries. Thank you!

**Pull request merged**
